name: tasky
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  camera_platform_interface: ^2.7.4
  camera_windows: ^0.2.2
  confirm_dialog: ^1.0.3
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  http_parser: ^4.0.2
  image_picker: ^1.1.1
  image_picker_for_web: ^3.0.4
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  intl_phone_number_input: ^0.7.4
  mime: ^1.0.5
  permission_handler: ^11.3.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.3
  transparent_image: ^2.0.1
  typed_data: ^1.3.2
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
